inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
